CREATE TABLE Ideas (
    Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    ProjectName VARCHAR(100) NOT NULL,
	Initials VARCHAR(5) NOT NULL,
	Description VARCHAR(1500) NOT NULL,
	Risk VARCHAR(1000),
	Team VARCHAR(100),
	PlanDescription VARCHAR(1000),
	ExpectedResults VARCHAR(1000), 
	[priority] INT,
	[status] INT DEFAULT 1,
	CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
	UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);
